services:
  - type: web
    name: smart_backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend_smart.wsgi:application"
    postDeployCommand: "python manage.py migrate --noinput"

